export const englistNames:{[key: string]:string} = {
  "en": "English",
  "zh-CN": "Simplified Chinese",
  "zh-TW": "Traditional Chinese",
  "ja": "Japanese",
  "ko": "Korean",
  "fr": "French",
  "de": "German",
  "es": "Spanish",
  "ru": "Russian",
  "pt-BR": "Portuguese (Brazil)",
  "it": "Italian",
  "ar": "Arabic",
  "hi": "Hindi",
  "th": "Thai",
  "vi": "Vietnamese",
  "id": "Indonesian",
  "tr": "Turkish",
  "pl": "Polish",
  "nl": "Dutch",
  "uk": "Ukrainian",
  "el": "Greek",
  "cs": "Czech",
  "hu": "Hungarian",
  "he": "Hebrew",
  "ro": "Romanian",
  "sv": "Swedish",
  "fi": "Finnish",
  "da": "Danish",
  "no": "Norwegian",
  "sk": "Slovak",
  "sr": "Serbian",
  "hr": "Croatian",
  "bg": "Bulgarian",
  "ms": "Malay",
  "fa": "Persian"
}
